name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      working-directory: ./foundation-zh
      run: npm install
    - name: test
      working-directory: ./foundation-zh
      run: npm test
    - name: linter
      working-directory: ./foundation-zh
      run: npm run lint
    env:
      CI: true
